heat_template_version: 2017-09-01

description: Infra LBaaS

parameters:
#-------------------#
# Stack Parameters  #
#-------------------#
  public_net:
    label: Public network address
    default: dfa37f36-5241-4a2e-9de5-3a85afe10952
    description: Public Network ID
    type: string
  dmz_network_net:
    label: DMZ network address
    default: 192.168.0.0/24
    description: Private network address (e.g. 192.168.0.0/24)
    type: string
  db_network_net:
    label: Database network address
    default: 192.168.1.0/24
    description: Private network address (e.g. 192.168.1.0/24)
    type: string
  flavor:
    default: 25cb69e2-c9ab-4498-8832-5f779d893b71
    description: Flavor of the servers
    type: string
    constraints:
    - custom_constraint: nova.flavor
  image:
    default: eb68545a-d538-4491-94eb-4aacfe191485
    description: Image to use to boot the servers
    type: string
    constraints:
    - custom_constraint: glance.image
  web_keypair:
    default: WEB
    description: Please create the keypair before launching this stack
    type: string
    constraints:
  db_keypair:
    default: DB
    description: Please create the keypair before launching this stack
    type: string
    constraints:
    - custom_constraint: nova.keypair
  lb_port:
    label: Load balancer Port
    default: 80
    description: Port used by the load balancer
    type: number
  app_port:
    label: Application Port
    default: 80
    description: Port used by the servers
    type: number


resources:
#--------------------#
# Network properties #
#--------------------#
  dmz_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: 'Security group for ICMP, HTTP and SSH'
      name: dmz-sec-group
      rules:
      - direction: egress
        ethertype: IPv4
        remote_ip_prefix: 0.0.0.0/0
      - direction: ingress
        protocol: icmp
      - direction: ingress
        ethertype: IPv4
        port_range_max: 80
        port_range_min: 80
        protocol: tcp
      - direction: ingress
        ethertype: IPv4
        port_range_max: 22
        port_range_min: 22
        protocol: tcp

  db_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: 'Security group for ICMP, MySQL and SSH'
      name: db-sec-group
      rules:
      - direction: egress
        ethertype: IPv4
        remote_ip_prefix: 0.0.0.0/0
      - direction: ingress
        protocol: icmp
      - direction: ingress
        ethertype: IPv4
        port_range_max: 3306
        port_range_min: 3306
        protocol: tcp
      - direction: ingress
        ethertype: IPv4
        port_range_max: 22
        port_range_min: 22
        protocol: tcp

  dmz_network:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: dmz-network
      shared: false

  dmz_subnet:
    type: OS::Neutron::Subnet
    depends_on: dmz_network
    properties:
      name: dmz-subnet
      network_id: { get_resource: dmz_network }
      cidr: { get_param: dmz_network_net }
      ip_version: 4
      enable_dhcp: true
      dns_nameservers:
      - 8.8.8.8
      - 8.8.4.4

  db_network:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: db-network
      shared: false

  db_subnet:
    type: OS::Neutron::Subnet
    depends_on: db_network
    properties:
      name: db-subnet
      network_id: { get_resource: db_network }
      cidr: { get_param: db_network_net }
      ip_version: 4
      enable_dhcp: true
      dns_nameservers:
      - 8.8.8.8
      - 8.8.4.4

#----------------------#
# Router for SourceNAT #
#----------------------#
  router:
    type: OS::Neutron::Router
    depends_on: dmz_subnet
    properties:
      name: router
      admin_state_up: true
      external_gateway_info:
        network: { get_param: public_net }

  dmz_router_interface:
    type: OS::Neutron::RouterInterface
    depends_on: router
    properties:
      router: { get_resource: router }
      subnet: { get_resource: dmz_subnet }
      
  db_router_interface:
    type: OS::Neutron::RouterInterface
    depends_on: router
    properties:
      router: { get_resource: router }
      subnet: { get_resource: db_subnet }

#-------------------------#
# Server nodes properties #
#-------------------------#
  db_srv_1:
    type: OS::Nova::Server
    depends_on: db_subnet
    properties:
      name: db-srv-1
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: db_keypair }
      security_groups: [ { get_resource: db_security_group } ]
      networks: [{ network: { get_resource: db_network }} ]
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #! /bin/sh -v
            sudo -i
            apt update
          params:
            $shared_ip: { get_param: flavor }

  db_srv_2:
    type: OS::Nova::Server
    depends_on: db_subnet
    properties:
      name: db-srv-2
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: db_keypair }
      security_groups: [ { get_resource: db_security_group } ]
      networks: [{ network: { get_resource: db_network }} ]
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #! /bin/sh -v
            sudo -i
            apt update
          params:
            $shared_ip: { get_param: flavor }

  web_srv_1:
    type: OS::Nova::Server
    depends_on: dmz_subnet
    properties:
      name: web-srv-1
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: web_keypair }
      security_groups: [ { get_resource: dmz_security_group } ]
      networks: [{ network: { get_resource: dmz_network }} ]
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #! /bin/sh -v
            sudo -i
            apt update
            apt install -y apache2 git php php-mcrypt php-mysql libapache2-mod-php
            rm -rf /var/www/html
            git clone https://github.com/binariocloud/chat.git -l /var/www
            touch /var/www/html/assets/chat.txt
            chmod 666 /var/www/html/assets/chat.txt
          params:
            $shared_ip: { get_param: flavor }

  web_srv_2:
    type: OS::Nova::Server
    depends_on: dmz_subnet
    properties:
      name: web-srv-2
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: web_keypair }
      security_groups: [ { get_resource: dmz_security_group } ]
      networks: [{ network: { get_resource: dmz_network }} ]
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #! /bin/sh -v
            sudo -i
            apt update
            apt install -y apache2 git php php-mcrypt php-mysql libapache2-mod-php
            rm -rf /var/www/html
            git clone https://github.com/binariocloud/chat.git -l /var/www
            touch /var/www/html/assets/chat.txt
            chmod 666 /var/www/html/assets/chat.txt
          params:
            $shared_ip: { get_param: flavor }

  web_srv_3:
    type: OS::Nova::Server
    depends_on: dmz_subnet
    properties:
      name: web-srv-3
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: web_keypair }
      security_groups: [ { get_resource: dmz_security_group } ]
      networks: [{ network: { get_resource: dmz_network }} ]
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #! /bin/sh -v
            sudo -i
            apt update
            apt install -y apache2 git php php-mcrypt php-mysql libapache2-mod-php
            rm -rf /var/www/html
            git clone https://github.com/binariocloud/chat.git -l /var/www
            touch /var/www/html/assets/chat.txt
            chmod 666 /var/www/html/assets/chat.txt
          params:
            $shared_ip: { get_param: flavor }

  web_srv_4:
    type: OS::Nova::Server
    depends_on: dmz_subnet
    properties:
      name: web-srv-4
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: web_keypair }
      security_groups: [ { get_resource: dmz_security_group } ]
      networks: [{ network: { get_resource: dmz_network }} ]
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #! /bin/sh -v
            sudo -i
            apt update
            apt install -y apache2 git php php-mcrypt php-mysql libapache2-mod-php
            rm -rf /var/www/html
            git clone https://github.com/binariocloud/chat.git -l /var/www
            touch /var/www/html/assets/chat.txt
            chmod 666 /var/www/html/assets/chat.txt
          params:
            $shared_ip: { get_param: flavor }

#--------------------------#
# Load Balancer properties #
#--------------------------#
  pool_member1:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_resource: pool }
      address: { get_attr: [ web_srv_1, first_address ]}
      protocol_port: { get_param: app_port }
      subnet: { get_resource: dmz_subnet }

  pool_member2:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_resource: pool }
      address: { get_attr: [ web_srv_2, first_address ]}
      protocol_port: { get_param: app_port }
      subnet: { get_resource: dmz_subnet }

  pool_member3:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_resource: pool }
      address: { get_attr: [ web_srv_3, first_address ]}
      protocol_port: { get_param: app_port }
      subnet: { get_resource: dmz_subnet }

  pool_member4:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_resource: pool }
      address: { get_attr: [ web_srv_4, first_address ]}
      protocol_port: { get_param: app_port }
      subnet: { get_resource: dmz_subnet }

  monitor:
    type: OS::Neutron::LBaaS::HealthMonitor
    properties:
      type: HTTP
      delay: 3
      max_retries: 3
      timeout: 5
      pool: { get_resource: pool }

  pool:
    type: OS::Neutron::LBaaS::Pool
    properties:
      lb_algorithm: ROUND_ROBIN
      protocol: HTTP
      listener: { get_resource: listener }

  listener:
    type: OS::Neutron::LBaaS::Listener
    properties:
      loadbalancer: { get_resource: loadbalancer }
      protocol: HTTP
      protocol_port: { get_param: lb_port }

  loadbalancer:
    type: OS::Neutron::LBaaS::LoadBalancer
    depends_on: dmz_router_interface
    properties:
      vip_subnet: { get_resource: dmz_subnet }

  lb_vip_floating_ip:
    type: OS::Neutron::FloatingIP
    depends_on: loadbalancer
    properties:
      floating_network_id: { get_param: public_net }
      port_id: { get_attr: [loadbalancer, vip_port_id] }

outputs:
  LBaaS_floating_ip:
    description: load balancer floating IP address
    value: { get_attr: [ lb_vip_floating_ip, floating_ip_address ] }
